name: Release

on:
  push:
    branches:
      - master

jobs:
  cache-pnpm:
    name: Cache Pnpm
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.13.0
      - run: |
          pnpm config set //pkgs.dev.azure.com/lumadev/_packaging/lumadev/npm/registry/:_password=${{ secrets.PAT_B64 }}
          pnpm config set //pkgs.dev.azure.com/lumadev/_packaging/lumadev/npm/:_password=${{ secrets.PAT_B64 }}
      - run: pnpm install --frozen-lockfile --prefer-offline
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.13.0
      - run: |
          pnpm config set //pkgs.dev.azure.com/lumadev/_packaging/lumadev/npm/registry/:_password=${{ secrets.PAT_B64 }}
          pnpm config set //pkgs.dev.azure.com/lumadev/_packaging/lumadev/npm/:_password=${{ secrets.PAT_B64 }}
      - run: pnpm install --frozen-lockfile --prefer-offline
      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
